name: playground

on:
  push:
    paths:
      - playground/**
      - .github/workflows/playground.yml

jobs:
  html5:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: html5
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
      - name: Deploy gh-pages
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: ${{ github.workflow }}/build_${{ github.workflow }}/html5
          target-folder: ${{ github.workflow }}
  krom-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: krom-linux
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
  linux-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: linux-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
  android-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: android-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
  windows-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: windows-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
  macos-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: macos-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
  ios-hl:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Build
        uses: tong/armory_gh_actions@v0.1.9
        with:
          publish: ios-hl
          blend: ${{ github.workflow }}/${{ github.workflow }}.blend
          blender:  latest/stable
